import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("correction requests save Malaysia time and clock-out approvals target open rows", async () => {
  const [script, employeeRoute, employeeSummaryRoute, adminRoute, adminHtml, css, clockRoute] = await Promise.all([
    readFile(new URL("../script.js", import.meta.url), "utf8"),
    readFile(new URL("../app/api/corrections/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/employee/summary/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/admin/live/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../HR ADMIN LIVE.html", import.meta.url), "utf8"),
    readFile(new URL("../style.css", import.meta.url), "utf8"),
    readFile(new URL("../app/api/attendance/clock/route.ts", import.meta.url), "utf8"),
  ]);

  assert.match(script, /`\$\{date\}T\$\{time\}:00\+08:00`/);
  assert.match(employeeRoute, /action\?: "cancel"/);
  assert.match(employeeRoute, /correctionId\?: string/);
  assert.match(employeeRoute, /SET status = 'cancelled'/);
  assert.match(employeeRoute, /admin_note = 'Cancelled by employee'/);
  assert.match(employeeRoute, /WHERE id = \? AND employee_id = \? AND status = 'pending'/);
  assert.match(employeeRoute, /Pending correction request was not found/);
  assert.match(employeeRoute, /function findTargetAttendanceForCorrection/);
  assert.match(employeeRoute, /clock_in_at IS NOT NULL AND clock_out_at IS NULL/);
  assert.match(employeeRoute, /ORDER BY clock_in_at DESC, updated_at DESC/);
  assert.doesNotMatch(employeeRoute, /SELECT \* FROM attendance WHERE employee_id = \? AND work_date = \?"/);
  assert.match(employeeSummaryRoute, /source, created_at, updated_at/);
  assert.match(employeeSummaryRoute, /clock_in_updated_at/);
  assert.match(employeeSummaryRoute, /clock_out_updated_at/);
  assert.match(employeeSummaryRoute, /report_edited_clock_in/);
  assert.match(employeeSummaryRoute, /report_edited_clock_out/);
  assert.match(employeeSummaryRoute, /report_clock_in_mark: reportClockMark\(row, "clock_in", correctionRows\)/);
  assert.match(employeeSummaryRoute, /report_clock_out_mark: reportClockMark\(row, "clock_out", correctionRows\)/);
  assert.match(employeeSummaryRoute, /function reportClockMark/);
  assert.match(employeeSummaryRoute, /return "corrected"/);
  assert.match(employeeSummaryRoute, /return Number\(row\[editedKey\] \|\| 0\) && row\[valueKey\] \? "edited" : ""/);
  assert.match(employeeSummaryRoute, /WITH base_rows AS/);
  assert.match(employeeSummaryRoute, /report_rows AS/);
  assert.match(employeeSummaryRoute, /field_overrides AS/);
  assert.match(employeeSummaryRoute, /live_open_rows AS/);
  assert.match(employeeSummaryRoute, /MAX\(clock_in_at\) AS live_open_clock_in_at/);
  assert.match(employeeSummaryRoute, /report_edited_clock_in, report_edited_clock_out, live_open_clock_in_at/);
  assert.match(employeeSummaryRoute, /day_keys AS/);
  assert.match(employeeSummaryRoute, /source = 'admin_report_edit'/);
  assert.match(employeeSummaryRoute, /source NOT LIKE 'admin_report_edit%'/);
  assert.match(employeeSummaryRoute, /source IN \('admin_report_edit_in', 'admin_report_edit_out'\)/);
  assert.match(employeeSummaryRoute, /MIN\(clock_in_at\) AS clock_in_at/);
  assert.match(employeeSummaryRoute, /MAX\(clock_out_at\) AS clock_out_at/);
  assert.match(employeeSummaryRoute, /SUM\(COALESCE\(total_minutes, 0\)\) AS total_minutes/);
  assert.match(employeeSummaryRoute, /COALESCE\(o\.has_clock_in_override, 0\) = 1/);
  assert.match(employeeSummaryRoute, /COALESCE\(o\.has_clock_out_override, 0\) = 1/);
  assert.match(employeeSummaryRoute, /CASE WHEN COALESCE\(o\.has_clock_in_override, 0\) = 1 THEN o\.override_clock_in_at ELSE COALESCE\(r\.clock_in_at, b\.clock_in_at\) END AS clock_in_at/);
  assert.match(employeeSummaryRoute, /CASE WHEN COALESCE\(o\.has_clock_out_override, 0\) = 1 THEN o\.override_clock_out_at ELSE COALESCE\(r\.clock_out_at, b\.clock_out_at\) END AS clock_out_at/);
  assert.match(employeeSummaryRoute, /LEFT JOIN base_rows b ON b\.work_date = d\.work_date/);
  assert.match(employeeSummaryRoute, /LEFT JOIN report_rows r ON r\.work_date = d\.work_date/);
  assert.match(employeeSummaryRoute, /LEFT JOIN field_overrides o ON o\.work_date = d\.work_date/);
  assert.match(employeeSummaryRoute, /LEFT JOIN live_open_rows l ON l\.work_date = d\.work_date/);
  assert.doesNotMatch(employeeSummaryRoute, /work_date NOT IN \(SELECT work_date FROM report_days\)/);
  assert.match(employeeSummaryRoute, /ORDER BY work_date DESC, updated_at DESC/);
  assert.match(employeeSummaryRoute, /created_at, reviewed_at/);
  assert.match(script, /sort\(compareAttendanceLatest\)/);
  assert.match(script, /function attendanceEditMarks/);
  assert.match(script, /function approvedCorrectionForField/);
  assert.match(script, /function attendanceDisplayTimes/);
  assert.match(script, /function parseLiveTimestamp/);
  assert.match(script, /function sameClockValue/);
  assert.match(script, /clockInUpdatedAt: row\.clock_in_updated_at \|\| row\.updated_at \|\| ""/);
  assert.match(script, /clockOutUpdatedAt: row\.clock_out_updated_at \|\| row\.updated_at \|\| ""/);
  assert.match(script, /reportEditedClockIn: Boolean\(Number\(row\.report_edited_clock_in \|\| 0\)\)/);
  assert.match(script, /reportEditedClockOut: Boolean\(Number\(row\.report_edited_clock_out \|\| 0\)\)/);
  assert.match(script, /hasReportMarks: Object\.prototype\.hasOwnProperty\.call\(row, "report_clock_in_mark"\) \|\| Object\.prototype\.hasOwnProperty\.call\(row, "report_clock_out_mark"\)/);
  assert.match(script, /clockInMark: row\.report_clock_in_mark \|\| ""/);
  assert.match(script, /clockOutMark: row\.report_clock_out_mark \|\| ""/);
  assert.match(script, /canClockOut: Boolean\(row\.live_open_clock_in_at\)/);
  assert.match(script, /liveClockIn: formatLiveTime\(row\.live_open_clock_in_at\)/);
  assert.match(script, /Object\.prototype\.hasOwnProperty\.call\(row, "canClockOut"\)/);
  assert.match(script, /row\.canClockOut && isOpenRecordStillActive\(row\.date\)/);
  assert.match(clockRoute, /AND source NOT LIKE 'admin_report_edit%'/);
  assert.match(script, /const fieldUpdatedAt = field === "clockIn" \? row\.clockInUpdatedAt : row\.clockOutUpdatedAt/);
  assert.match(script, /parseLiveTimestamp\(b\.reviewedAt \|\| b\.createdAt \|\| ""\)/);
  assert.match(script, /sameClockValue\(correction\[key\], row\[field\]\) \|\| isSameOrNewer\(correction\.reviewedAt \|\| correction\.createdAt, fieldUpdatedAt \|\| row\.updatedAt \|\| row\.createdAt\)/);
  assert.doesNotMatch(script, /return correction\[key\] === row\[field\]/);
  assert.match(employeeSummaryRoute, /r\.clock_in_at IS NOT NULL OR COALESCE\(o\.has_clock_in_override, 0\) = 1/);
  assert.match(employeeSummaryRoute, /r\.clock_out_at IS NOT NULL OR COALESCE\(o\.has_clock_out_override, 0\) = 1/);
  assert.match(script, /if \(row\.hasReportMarks\) \{/);
  assert.match(script, /clockIn: row\.clockInMark \|\| ""/);
  assert.match(script, /clockOut: row\.clockOutMark \|\| ""/);
  assert.match(script, /const display = attendanceDisplayTimes\(row, corrections\)/);
  assert.match(script, /class="time-mark corrected"/);
  assert.match(css, /\.time-mark\.edited/);
  assert.match(css, /\.time-mark\.corrected/);
  assert.match(adminRoute, /const existingRecord = await findTargetAttendanceForCorrection\(db, correction\)/);
  assert.match(adminRoute, /action: "save_report_attendance_times"/);
  assert.match(adminRoute, /source = 'admin_report_edit'/);
  assert.match(adminRoute, /source = 'admin_report_edit_archived'/);
  assert.match(adminRoute, /source <> 'admin_report_edit_archived'/);
  assert.match(adminRoute, /function archiveReportAttendanceRows/);
  assert.match(adminRoute, /let previousRegularMinutes = 0/);
  assert.match(adminRoute, /function reportFieldOverrides/);
  assert.match(adminRoute, /admin_report_edit_in/);
  assert.match(adminRoute, /admin_report_edit_out/);
  assert.match(adminRoute, /source = CASE WHEN source = 'admin_report_edit' THEN source ELSE 'admin_adjustment' END/);
  assert.match(employeeRoute, /source = CASE WHEN source = 'admin_report_edit' THEN source ELSE 'admin_adjustment' END/);
  assert.equal(
    (adminRoute.match(/updated_at = CASE WHEN source = 'admin_report_edit' THEN updated_at ELSE CURRENT_TIMESTAMP END/g) || []).length,
    2,
  );
  assert.equal(
    (employeeRoute.match(/updated_at = CASE WHEN source = 'admin_report_edit' THEN updated_at ELSE CURRENT_TIMESTAMP END/g) || []).length,
    2,
  );
  assert.match(adminRoute, /function reportTimeSegments/);
  assert.match(adminRoute, /monthly_report_time_edit/);
  assert.match(adminRoute, /monthly_report_time_restore/);
  assert.match(adminRoute, /SET attendance_id = \?, status = \?/);
  assert.match(adminRoute, /let reviewedAttendanceId = correction\.attendance_id/);
  assert.match(adminRoute, /action: "load_live_data"/);
  assert.match(adminRoute, /requireAdmin\(db, request, "hrToken" in payload \? payload\.hrToken : undefined\)/);
  assert.match(adminRoute, /bodyToken\.trim\(\)/);
  assert.doesNotMatch(adminRoute, /searchParams\.get\("hrToken"\)/);
  assert.match(adminHtml, /function approvedCorrectionTimes/);
  assert.match(adminHtml, /function correctionRequestedSummary/);
  assert.match(adminHtml, /function correctionRequestedField/);
  assert.match(adminHtml, /function correctionSourceTime/);
  assert.match(adminHtml, /const reportRow = employeeAttendanceByDate\(request\.employee_id, request\.requested_date\)/);
  assert.match(adminHtml, /reportRow\?\.clockIn \|\| original\?\.clock_in_at/);
  assert.match(adminHtml, /reportRow\?\.clockOut \|\| original\?\.clock_out_at/);
  assert.match(adminHtml, /return `\$\{label\}: <strong>\$\{escapeHtml\(dateText\)\}, \$\{timeText\}<\/strong>`/);
  assert.match(adminHtml, /function wait\(ms\)/);
  assert.match(adminHtml, /for \(let attempt = 0; attempt < 3; attempt \+= 1\)/);
  assert.match(adminHtml, /body = JSON\.stringify\(\{ \.\.\.payload, hrToken: savedToken \}\)/);
  assert.match(adminHtml, /action: "load_live_data"/);
  assert.match(adminHtml, /text\/plain;charset=UTF-8/);
  assert.doesNotMatch(adminHtml, /headers\.Authorization/);
  assert.match(adminHtml, /Cannot connect to live database\. Click Refresh again\./);
  assert.match(adminHtml, /async function loadLiveData\(force = false, showError = false\)/);
  assert.match(adminHtml, /if \(showError \|\| !hasExistingData\)/);
  assert.doesNotMatch(adminHtml, /mode: "cors"/);
  assert.doesNotMatch(adminHtml, /credentials: "omit"/);
  assert.doesNotMatch(adminHtml, /Live database reconnecting\.\.\./);
  assert.match(adminHtml, /}, 30000\)/);
  assert.match(adminHtml, /let refreshQueued = false/);
  assert.match(adminHtml, /if \(loading\) \{/);
  assert.match(adminHtml, /const clockOut = approved\.find\(item => item\.requested_clock_out_at\)/);
  assert.match(adminHtml, /clockOut: clockOut\?\.requested_clock_out_at \|\| ""/);
  assert.match(adminHtml, /const inRow = inRows\[0\] \|\| null/);
  assert.match(adminHtml, /const outRow = outRows\[outRows\.length - 1\] \|\| null/);
  assert.match(adminHtml, /function isReportFieldMarker/);
  assert.match(adminHtml, /const rowLastOut = outMarker \? outMarker\.clock_out_at \|\| "" : outRow\?\.clock_out_at \|\| ""/);
  assert.match(adminHtml, /const lastOut = correctionOutWins \? approvedTimes\.clockOut : rowLastOut/);
  assert.match(adminHtml, /manualEdit/);
  assert.match(adminHtml, /correctedTime/);
  assert.match(adminHtml, /function reportCorrectionWins/);
  assert.match(adminHtml, /function isSameOrNewer/);
  assert.match(adminHtml, /function sameReportInstant/);
  assert.match(adminHtml, /const correctionInWins = Boolean\(approvedTimes\.clockIn\) && \(sameReportInstant\(approvedTimes\.clockIn, rowFirstIn\) \|\| isSameOrNewer\(approvedTimes\.clockInReviewedAt, inUpdatedAt\)\)/);
  assert.match(adminHtml, /const correctionOutWins = Boolean\(approvedTimes\.clockOut\) && \(sameReportInstant\(approvedTimes\.clockOut, rowLastOut\) \|\| isSameOrNewer\(approvedTimes\.clockOutReviewedAt, outUpdatedAt\)\)/);
  assert.doesNotMatch(adminHtml, /clearCalculatedReportEdits\(approvedCorrection\.employee_id, approvedCorrection\.requested_date\)/);
  assert.match(adminHtml, /class="highlightTime"/);
  assert.match(adminHtml, /function reportPaidWorkMinutes/);
  assert.match(adminHtml, /function normalizeReportTime/);
  assert.match(adminHtml, /function calculatedReportValues/);
  assert.match(adminHtml, /ms < afterMs/);
  assert.match(adminRoute, /ms < afterMs/);
  assert.match(adminRoute, /outMs >= inMs/);
  assert.match(adminHtml, /hasTimes: false/);
  assert.match(adminHtml, /hasTimes: true/);
  assert.match(adminHtml, /const work = calculated\.hasTimes \? calculated\.work : reportHours\(attendanceRow\?\.actualMinutes\)/);
  assert.match(adminHtml, /const overtime = calculated\.hasTimes \? calculated\.overtime : reportHours\(reportOvertimeMinutes\(attendanceRow, day\)\)/);
  assert.match(adminHtml, /const short = calculated\.hasTimes \? calculated\.short : reportHours\(reportShortMinutes\(attendanceRow, day, leaveTaken\)\)/);
  assert.match(adminHtml, /function reportHours\(minutes, showZero = false\)/);
  assert.match(adminHtml, /const showZeroWork = outMs === inMs/);
  assert.match(adminHtml, /work: reportHours\(workMinutes, showZeroWork\)/);
  assert.match(adminHtml, /function isHalfLeaveText/);
  assert.match(adminHtml, /function reportWorkingWindowMinutes/);
  assert.match(adminHtml, /if \(inMinutes <= start \+ 15\) lateShort = 0/);
  assert.match(adminHtml, /if \(isHalfLeaveText\(leaveTaken\)\)/);
  assert.match(adminHtml, /Math\.max\(0, 240 - reportWorkingWindowMinutes\(attendanceRow, day\)\)/);
  assert.match(adminHtml, /const workShort = Math\.max\(0, requiredMinutes - Number\(attendanceRow\.actualMinutes \|\| 0\)\)/);
  assert.match(adminHtml, /return Math\.max\(lateShort, earlyOut, workShort\)/);
  assert.doesNotMatch(adminHtml, /return Math\.max\(lateShort, earlyOut\)/);
  assert.match(adminHtml, /function isEditableReportField/);
  assert.match(adminHtml, /function reportFieldWasEdited/);
  assert.match(adminHtml, /reportEditedClockIn: Boolean\(inMarker \|\| reportSegmentRows\.some\(row => row\.clock_in_at\)\) && !correctionInWins/);
  assert.match(adminHtml, /reportEditedBreak: Boolean\(breakTime\)/);
  assert.match(adminHtml, /if \(!isEditableReportField\(field\)\) return fallback/);
  assert.match(adminHtml, /if \(reportCorrectionWins\(employeeId, dateKey, field\)\) return fallback/);
  assert.match(adminHtml, /const manualEdit = editableField && !correctionWins && \(Object\.prototype\.hasOwnProperty\.call\(monthlyReportEdits, key\) \|\| reportFieldWasEdited\(employeeId, dateKey, field\)\)/);
  assert.match(adminHtml, /if \(!isEditableReportField\(field\)\)/);
  assert.match(adminHtml, /break: reportValue\(employee\.id, dateKey, "break", reportTime\(attendanceRow\?\.breakTime\)\)/);
  assert.match(adminHtml, /resume: reportValue\(employee\.id, dateKey, "resume", reportTime\(attendanceRow\?\.resumeTime\)\)/);
  assert.match(adminHtml, /const liveRows = timeRows/);
  assert.match(adminHtml, /liveRows\.forEach\(row =>/);
  assert.match(adminHtml, /delete nextEdits\[reportEditKey\(employeeId, row\.dateKey, field\)\]/);
  assert.doesNotMatch(adminHtml, /const restoreRows = \[\.\.\.reportRows\.keys\(\)\]/);
  assert.match(adminHtml, /action: "save_report_attendance_times"/);
  assert.match(adminHtml, /action: "restore_report_attendance_times"/);
  assert.match(adminHtml, /data-cancel-report/);
  assert.match(adminHtml, /Cancelled edit \|/);
  assert.match(adminHtml, /row\.source === "admin_report_edit"/);
  assert.match(adminHtml, /editedFields: \["in", "break", "resume", "out"\]\.filter/);
  assert.match(adminHtml, /REPORT_TIME_FIELDS = new Set\(\["in", "break", "resume", "out"\]\)/);
  assert.match(adminHtml, /contenteditable="\$\{editable \? "true" : "false"\}"/);
  assert.match(adminHtml, /refreshReportRow\(cell\.closest\("tr"\), false\)/);
  assert.match(adminHtml, /refreshReportRow\(cell\.closest\("tr"\), true\)/);
  assert.match(adminHtml, /function originalReportValue/);
  assert.match(adminHtml, /function reportFieldShouldSave/);
  assert.match(adminHtml, /reportFieldWasEdited\(employeeId, dateKey, field\)/);
  assert.match(adminHtml, /return reportFieldShouldSave\(employeeId, dateKey, field, nextEdits\)/);
  assert.match(adminHtml, /editedFields: \["in", "break", "resume", "out"\]\.filter\(field => reportFieldShouldSave\(employeeId, dateKey, field, nextEdits\)\)/);
  assert.match(adminHtml, /const regularSpan = Math\.max\(0, Math\.round/);
  assert.match(adminHtml, /const breakDeduction = day >= 1 && day <= 5 && regularSpan > 300 \? 60 : 0/);
  assert.match(adminHtml, /scheduledDateTimeMs\(dateKey, end \+ 15\)/);
  assert.match(adminHtml, /scheduledDateTimeMs\(attendanceRow\.dateKey, end \+ 15\)/);
  assert.doesNotMatch(adminHtml, /lateShort > 60\) lateShort -= 60/);
  assert.match(adminHtml, /const regularCap = day === 6 \? 240 : 480/);
  assert.match(adminHtml, /Math\.min\(Math\.max\(0, regularSpan - breakDeduction\), regularCap\) \+ overtime/);
  assert.match(adminHtml, /const outMs = Date\.parse\(attendanceRow\.clockOut \|\| ""\)/);
  assert.match(adminHtml, /Math\.round\(\(endMs - outMs\) \/ 60000\)/);
  assert.doesNotMatch(adminHtml, /Math\.max\(0, end - outMinutes\)/);
  assert.match(adminHtml, /20260805-zero-overtime-fallback/);
  assert.doesNotMatch(adminHtml, /<th>Sche<\/th>/);
  assert.doesNotMatch(adminHtml, /<th>Diff OT<\/th>/);
  assert.doesNotMatch(adminHtml, /editableReportCell\(employee\.id, dateKey, "schedule"/);
  assert.doesNotMatch(adminHtml, /editableReportCell\(employee\.id, dateKey, "diffOt"/);
});
