import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("approved corrections update attendance and highlight changed times", async () => {
  const [script, employeeRoute, employeeSummaryRoute, adminRoute, adminHtml, css, clockRoute, reconciliation] = await Promise.all([
    readFile(new URL("../script.js", import.meta.url), "utf8"),
    readFile(new URL("../app/api/corrections/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/employee/summary/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/admin/live/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../HR ADMIN LIVE.html", import.meta.url), "utf8"),
    readFile(new URL("../style.css", import.meta.url), "utf8"),
    readFile(new URL("../app/api/attendance/clock/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../db/attendance-reconciliation.ts", import.meta.url), "utf8"),
  ]);
  const adminReviewSection = adminRoute.slice(
    adminRoute.indexOf("async function reviewCorrectionRequest"),
    adminRoute.indexOf("async function saveReportAttendanceTimes"),
  );
  const patchReviewSection = employeeRoute.slice(
    employeeRoute.indexOf("export async function PATCH"),
    employeeRoute.indexOf("type CorrectionMissingType"),
  );

  assert.match(script, /`\$\{date\}T\$\{time\}:00\+08:00`/);
  assert.match(employeeRoute, /action\?: "cancel"/);
  assert.match(employeeRoute, /correctionId\?: string/);
  assert.match(employeeRoute, /SET status = 'cancelled'/);
  assert.match(employeeRoute, /admin_note = 'Cancelled by employee'/);
  assert.match(employeeRoute, /WHERE id = \? AND employee_id = \? AND status = 'pending'/);
  assert.match(employeeRoute, /Pending correction request was not found/);
  assert.match(employeeRoute, /function findTargetAttendanceForCorrection/);
  assert.match(employeeRoute, /clock_in_at IS NOT NULL AND clock_out_at IS NULL/);
  assert.match(employeeRoute, /ORDER BY clock_in_at DESC, updated_at DESC/);
  assert.doesNotMatch(employeeRoute, /SELECT \* FROM attendance WHERE employee_id = \? AND work_date = \?"/);
  assert.match(employeeSummaryRoute, /reconcileAttendanceRows/);
  assert.match(employeeSummaryRoute, /source <> 'admin_report_edit_archived'/);
  assert.match(employeeSummaryRoute, /WHERE status = 'approved' AND leave_type = 'leave'/);
  assert.match(employeeSummaryRoute, /ORDER BY COALESCE\(reviewed_at, created_at\) DESC, created_at DESC/);
  assert.match(employeeSummaryRoute, /report_clock_in_mark: reportClockMark\(row, "clock_in", correctionRows\)/);
  assert.match(employeeSummaryRoute, /report_clock_out_mark: reportClockMark\(row, "clock_out", correctionRows\)/);
  assert.match(employeeSummaryRoute, /function reportClockMark/);
  assert.match(employeeSummaryRoute, /return "corrected"/);
  assert.match(employeeSummaryRoute, /return Number\(row\[editedKey\] \|\| 0\) && row\[valueKey\] \? "edited" : ""/);
  assert.match(reconciliation, /function newestCandidate/);
  assert.match(reconciliation, /REPORT_IN_SOURCE/);
  assert.match(reconciliation, /REPORT_OUT_SOURCE/);
  assert.match(reconciliation, /break_at: breakAt/);
  assert.match(reconciliation, /resume_at: resumeAt/);
  assert.match(reconciliation, /report_segments_effective/);
  assert.match(reconciliation, /live_open_clock_in_at/);
  assert.match(reconciliation, /clockIn\.source !== "base"/);
  assert.match(reconciliation, /clockOut\.source !== "base"/);
  assert.match(reconciliation, /baseAdjustmentPreservesOverride\(clockIn, inMarker, "clock_in_at"\)/);
  assert.match(reconciliation, /baseAdjustmentPreservesOverride\(clockOut, outMarker, "clock_out_at"\)/);
  assert.match(reconciliation, /priority > best\.priority/);
  assert.match(employeeSummaryRoute, /created_at, reviewed_at/);
  assert.match(script, /sort\(compareAttendanceLatest\)/);
  assert.match(script, /function attendanceEditMarks/);
  assert.match(script, /function approvedCorrectionForField/);
  assert.match(script, /function attendanceDisplayTimes/);
  assert.doesNotMatch(script, /if \(Number\.isFinite\(Number\(row\.overtimeMinutes\)\)\) return Number\(row\.overtimeMinutes \|\| 0\)/);
  assert.match(script, /function parseLiveTimestamp/);
  assert.match(script, /function sameClockValue/);
  assert.match(script, /clockInUpdatedAt: row\.clock_in_updated_at \|\| row\.updated_at \|\| ""/);
  assert.match(script, /clockOutUpdatedAt: row\.clock_out_updated_at \|\| row\.updated_at \|\| ""/);
  assert.match(script, /reportEditedClockIn: Boolean\(Number\(row\.report_edited_clock_in \|\| 0\)\)/);
  assert.match(script, /reportEditedBreak: Boolean\(Number\(row\.report_edited_break \|\| 0\)\)/);
  assert.match(script, /reportEditedResume: Boolean\(Number\(row\.report_edited_resume \|\| 0\)\)/);
  assert.match(script, /reportEditedClockOut: Boolean\(Number\(row\.report_edited_clock_out \|\| 0\)\)/);
  assert.match(script, /hasReportMarks: Object\.prototype\.hasOwnProperty\.call\(row, "report_clock_in_mark"\) \|\| Object\.prototype\.hasOwnProperty\.call\(row, "report_clock_out_mark"\)/);
  assert.match(script, /clockInMark: row\.report_clock_in_mark \|\| ""/);
  assert.match(script, /clockOutMark: row\.report_clock_out_mark \|\| ""/);
  assert.match(script, /const canClockOut = Boolean\(row\.clock_in_at && !row\.clock_out_at\)/);
  assert.match(script, /liveClockIn: formatLiveTime\(canClockOut \? row\.clock_in_at : null\)/);
  assert.match(script, /row\.clockIn && !row\.clockOut && isOpenRecordStillActive\(row\.date\)/);
  assert.match(clockRoute, /AND source = 'qr_gps'/);
  assert.match(clockRoute, /AND source IN \('qr_gps', 'admin_adjustment'\)/);
  assert.match(clockRoute, /CASE WHEN COALESCE\(f\.has_clock_in_override, 0\) = 1 THEN f\.override_clock_in_at ELSE q\.clock_in_at END AS clock_in_at/);
  assert.match(clockRoute, /CASE WHEN COALESCE\(f\.has_clock_out_override, 0\) = 1 THEN f\.override_clock_out_at ELSE q\.clock_out_at END AS clock_out_at/);
  assert.match(clockRoute, /action: "clock_in_existing"/);
  assert.match(clockRoute, /findQrAttendanceForDate/);
  assert.match(clockRoute, /Attendance already completed for today/);
  assert.doesNotMatch(clockRoute, /findLastCompletedSession/);
  assert.doesNotMatch(clockRoute, /calculateBreakReturnLateMinutes/);
  assert.doesNotMatch(clockRoute, /Clock out is required before the next clock in/);
  assert.match(script, /const fieldUpdatedAt = field === "clockIn" \? row\.clockInUpdatedAt : row\.clockOutUpdatedAt/);
  assert.match(employeeSummaryRoute, /approvedCorrectionMatchesField\(row, correction, field\)/);
  assert.match(employeeSummaryRoute, /approvedCorrectionMatchesField,\s+parseAttendanceTimestamp,\s+reconcileAttendanceRows/);
  assert.match(reconciliation, /const fieldUpdatedAt = Number\(row\[editedKey\] \|\| 0\)/);
  assert.match(reconciliation, /report_clock_in_updated_at: reportEditedClockIn/);
  assert.match(reconciliation, /report_clock_out_updated_at: reportEditedClockOut/);
  assert.doesNotMatch(script, /return correction\[key\] === row\[field\]/);
  assert.match(reconciliation, /timeCandidate\(inMarker, "clock_in_at", "override", 3, true\)/);
  assert.match(reconciliation, /timeCandidate\(outMarker, "clock_out_at", "override", 3, true\)/);
  assert.match(script, /if \(row\.hasReportMarks\) \{/);
  assert.match(script, /clockIn: row\.clockInMark \|\| ""/);
  assert.match(script, /breakTime: row\.reportEditedBreak && row\.breakTime \? "edited" : ""/);
  assert.match(script, /resumeTime: row\.reportEditedResume && row\.resumeTime \? "edited" : ""/);
  assert.match(script, /clockOut: row\.clockOutMark \|\| ""/);
  assert.match(script, /const display = attendanceDisplayTimes\(row, corrections\)/);
  assert.match(script, /function employeeHistoryTimeCell/);
  assert.doesNotMatch(script, /employeeHistoryTimeCell\(display\.breakTime, marks\.breakTime\)/);
  assert.doesNotMatch(script, /employeeHistoryTimeCell\(display\.resumeTime, marks\.resumeTime\)/);
  assert.match(script, /class="time-mark corrected"/);
  assert.match(css, /\.time-mark\.edited/);
  assert.match(css, /\.time-mark\.corrected/);
  assert.match(css, /\.history-time-cell\.manualEdit,[\s\S]*\.history-time-cell\.correctedTime \.history-time-value \{\s+background: transparent !important;\s+box-shadow: none !important;\s+border: 0 !important;\s+color: inherit !important;\s+font-weight: inherit !important;/);
  assert.match(adminHtml, /\.editableCell\.manualEdit \{\s+background: #e9f2ff;\s+box-shadow: inset 0 0 0 1px #7aa7d9;\s+font-weight: 800;/);
  assert.match(adminHtml, /\.editableCell\.correctedTime \{\s+background: #fff2bf;\s+box-shadow: inset 0 0 0 1px #d2a310;[\s\S]*font-weight: 800;/);
  assert.match(script, /function employeeHistoryTimeCell\(value\) \{\s+const text = value \|\| "";/);
  assert.doesNotMatch(script, /function employeeHistoryTimeCell\(value\)[\s\S]{0,250}(correctedTime|manualEdit)/);
  assert.match(script, /function formatLiveTime\(value\) \{\s+if \(!value\) return "";\s+const text = String\(value\)\.trim\(\);\s+if \(\/\^\\d\{1,2\}:\\d\{2\}\$\/\.test\(text\)\) return text\.padStart\(5, "0"\);/);
  assert.match(script, /toLocaleTimeString\("en-MY", \{ timeZone: "Asia\/Kuala_Lumpur", hour: "2-digit", minute: "2-digit", hour12: false \}\)/);
  assert.match(adminHtml, /toLocaleTimeString\("en-MY", \{\s+timeZone: "Asia\/Kuala_Lumpur",\s+hour: "2-digit",\s+minute: "2-digit",\s+hour12: false\s+\}\)/);
  assert.doesNotMatch(adminReviewSection, /attendanceChanged: false/);
  assert.doesNotMatch(patchReviewSection, /attendanceChanged: false/);
  assert.doesNotMatch(adminReviewSection, /COALESCE\(\?, clock_(?:in|out)_at\)/);
  assert.doesNotMatch(patchReviewSection, /COALESCE\(\?, clock_(?:in|out)_at\)/);
  assert.match(adminReviewSection, /approvedCorrectionTimes\(currentAttendance, correction\)/);
  assert.match(patchReviewSection, /approvedCorrectionTimes\(currentAttendance, correction\)/);
  assert.match(adminReviewSection, /SET clock_in_at = \?,\s+clock_out_at = \?/);
  assert.match(patchReviewSection, /SET clock_in_at = \?,\s+clock_out_at = \?/);
  assert.match(adminReviewSection, /total_minutes = 0, late_minutes = 0, early_leave_minutes = 0/);
  assert.match(patchReviewSection, /total_minutes = 0, late_minutes = 0, early_leave_minutes = 0/);
  assert.match(adminReviewSection, /source NOT LIKE 'admin_report_edit%'/);
  assert.match(employeeRoute, /source NOT LIKE 'admin_report_edit%'/);
  assert.match(employeeRoute, /effectiveAttendance \? JSON\.stringify\(effectiveAttendance\) : null/);
  assert.match(employeeRoute, /A valid requested time is required for every missing clock field/);
  assert.match(adminReviewSection, /UPDATE attendance\s/);
  assert.match(adminReviewSection, /INSERT INTO attendance\s/);
  assert.match(patchReviewSection, /UPDATE attendance\s/);
  assert.match(patchReviewSection, /INSERT INTO attendance\s/);
  assert.match(adminRoute, /action: "save_report_attendance_times"/);
  assert.match(adminRoute, /if \(breakMs != null \|\| resumeMs != null\)/);
  assert.match(adminRoute, /\{ clockInAt: iso\(inMs\), clockOutAt: iso\(breakMs\) \}/);
  assert.match(adminRoute, /\{ clockInAt: iso\(resumeMs\), clockOutAt: iso\(outMs\) \}/);
  assert.match(adminRoute, /const completeSegment = Boolean/);
  assert.match(adminRoute, /\? "pending_review"/);
  assert.match(adminRoute, /'admin_report_edit'/);
  assert.match(adminRoute, /admin_report_edit_resume/);
  assert.match(adminRoute, /source = 'admin_report_edit_archived'/);
  assert.match(adminRoute, /source <> 'admin_report_edit_archived'/);
  assert.match(adminRoute, /function archiveReportAttendanceRows/);
  assert.match(adminRoute, /let previousRegularMinutes = 0/);
  assert.match(adminRoute, /function reportFieldOverrides/);
  assert.match(adminRoute, /const preservedEditedFields = await reportEditedFieldsForDate\(db, payload\.employeeId, dateKey\)/);
  assert.match(adminRoute, /const editedFields = new Set\(\[\.\.\.preservedEditedFields, \.\.\.\(row\.editedFields \?\? \[\]\)\]\)/);
  assert.match(adminRoute, /if \(Number\(resolved\?\.report_edited_clock_in \|\| 0\)\) fields\.push\("in"\)/);
  assert.match(adminRoute, /if \(Number\(resolved\?\.report_edited_clock_out \|\| 0\)\) fields\.push\("out"\)/);
  assert.match(adminRoute, /admin_report_edit_in/);
  assert.match(adminRoute, /admin_report_edit_out/);
  assert.match(adminRoute, /function reportTimeSegments/);
  assert.match(adminRoute, /monthly_report_time_edit/);
  assert.doesNotMatch(adminRoute, /restore_report_attendance_times|monthly_report_time_restore|restoreReportAttendanceTimes/);
  assert.match(adminReviewSection, /SET attendance_id = \?, status = \?/);
  assert.match(adminRoute, /action: "load_live_data"/);
  assert.match(adminRoute, /requireAdmin\(db, request, "hrToken" in payload \? payload\.hrToken : undefined\)/);
  assert.match(adminRoute, /bodyToken\.trim\(\)/);
  assert.doesNotMatch(adminRoute, /searchParams\.get\("hrToken"\)/);
  assert.match(adminHtml, /function approvedCorrectionTimes/);
  assert.match(adminHtml, /const rowFirstIn = row \? row\.clock_in_at \|\| "" : approvedTimes\.clockIn \|\| ""/);
  assert.match(adminHtml, /const rowLastOut = row \? row\.clock_out_at \|\| "" : approvedTimes\.clockOut \|\| ""/);
  assert.doesNotMatch(adminHtml, /row\?\.clock_in_at \|\| approvedTimes\.clockIn/);
  assert.doesNotMatch(adminHtml, /row\?\.clock_out_at \|\| approvedTimes\.clockOut/);
  assert.match(adminHtml, /function correctionRequestedSummary/);
  assert.match(adminHtml, /function correctionRequestedField/);
  assert.match(adminHtml, /function correctionSourceTime/);
  assert.match(adminHtml, /const reportRow = employeeAttendanceByDate\(request\.employee_id, request\.requested_date\)/);
  assert.match(adminHtml, /reportRow\?\.clockIn \|\| original\?\.clock_in_at/);
  assert.match(adminHtml, /reportRow\?\.clockOut \|\| original\?\.clock_out_at/);
  assert.match(adminHtml, /return `\$\{label\}: <strong>\$\{escapeHtml\(dateText\)\}, \$\{timeText\}<\/strong>`/);
  assert.match(adminHtml, /function wait\(ms\)/);
  assert.match(adminHtml, /for \(let attempt = 0; attempt < 3; attempt \+= 1\)/);
  assert.match(adminHtml, /body = JSON\.stringify\(useAuthorizationHeader \? payload : \{ \.\.\.payload, hrToken: savedToken \}\)/);
  assert.match(adminHtml, /action: "load_live_data"/);
  assert.match(adminHtml, /allowAuthHeaderFallback: true,\s+body: JSON\.stringify\(\{ action: "load_live_data"/);
  assert.match(adminHtml, /text\/plain;charset=UTF-8/);
  assert.match(adminHtml, /headers\.Authorization = `Bearer \$\{savedToken\}`/);
  assert.match(adminHtml, /return await requestWithToken\(false\)/);
  assert.match(adminHtml, /return await requestWithToken\(true\)/);
  assert.match(adminHtml, /if \(allowAuthHeaderFallback && savedToken && originalBody\)/);
  assert.match(adminHtml, /Live connection interrupted\. Current data is kept; try again in a moment\./);
  assert.match(adminHtml, /Live connection interrupted\. Keeping current view\./);
  assert.match(adminHtml, /async function loadLiveData\(force = false, showError = false\)/);
  assert.match(adminHtml, /if \(showError \|\| !hasExistingData\)/);
  assert.match(adminHtml, /const previousEditingEmployeeId = editingEmployeeId/);
  assert.match(adminHtml, /editingEmployeeId = "";\s+saveRow\.disabled = true;\s+await adminAction\(payload, "Saving employee\.\.\."\);\s+renderEmployees\(\);/);
  assert.doesNotMatch(adminHtml, /mode: "cors"/);
  assert.doesNotMatch(adminHtml, /credentials: "omit"/);
  assert.doesNotMatch(adminHtml, /Live database reconnecting\.\.\./);
  assert.match(adminHtml, /}, 30000\)/);
  assert.match(adminHtml, /let refreshQueued = false/);
  assert.match(adminHtml, /if \(loading\) \{/);
  assert.match(adminHtml, /function isReportFieldMarker/);
  assert.match(adminHtml, /const reportInRows = reportSegmentRows\.filter\(row => row\.clock_in_at\)/);
  assert.match(adminHtml, /const reportOutRows = reportSegmentRows\.filter\(row => row\.clock_out_at\)/);
  assert.match(adminHtml, /const baseInCandidate = newestReportTimeCandidate\(baseRows\.map\(row => reportTimeCandidate\(row, "clock_in_at"\)\)\)/);
  assert.match(adminHtml, /const baseOutCandidate = newestReportTimeCandidate\(baseRows\.map\(row => reportTimeCandidate\(row, "clock_out_at"\)\)\)/);
  assert.match(adminHtml, /const inCandidate = newestReportTimeCandidate/);
  assert.match(adminHtml, /baseInCandidate/);
  assert.match(adminHtml, /baseOutCandidate/);
  assert.match(adminHtml, /const rowFirstIn = inCandidate\?\.value \|\| ""/);
  assert.match(adminHtml, /function newestReportTimeCandidate/);
  assert.match(adminHtml, /const lastOut = correctionOutWins \? approvedTimes\.clockOut : rowLastOut/);
  assert.match(adminHtml, /manualEdit/);
  assert.match(adminHtml, /correctedTime/);
  assert.match(adminHtml, /function reportCorrectionWins/);
  assert.match(adminHtml, /function isSameOrNewer/);
  assert.match(adminHtml, /function sameReportInstant/);
  assert.match(adminHtml, /const correctionInWins/);
  assert.match(adminHtml, /const correctionOutWins/);
  assert.doesNotMatch(adminHtml, /clearCalculatedReportEdits\(approvedCorrection\.employee_id, approvedCorrection\.requested_date\)/);
  assert.match(adminHtml, /class="highlightTime"/);
  assert.match(adminHtml, /function reportPaidWorkMinutes/);
  assert.match(adminHtml, /function normalizeReportTime/);
  assert.match(adminHtml, /function calculatedReportValues/);
  assert.match(adminHtml, /ms < afterMs/);
  assert.match(adminRoute, /ms < afterMs/);
  assert.match(adminRoute, /Date\.parse\(segment\.clockOutAt\) > Date\.parse\(segment\.clockInAt\)/);
  assert.match(adminHtml, /hasTimes: false/);
  assert.match(adminHtml, /hasTimes: true/);
  assert.match(adminHtml, /const work = calculated\.hasTimes \? calculated\.work : reportHours\(attendanceRow\?\.actualMinutes\)/);
  assert.match(adminHtml, /const overtime = calculated\.hasTimes \? calculated\.overtime : reportHours\(reportOvertimeMinutes\(attendanceRow, day\)\)/);
  assert.match(adminHtml, /const short = calculated\.hasTimes \? calculated\.short : reportHours\(reportShortMinutes\(attendanceRow, day, leaveTaken\)\)/);
  assert.match(adminHtml, /return Math\.min\(240, Math\.max\(lateShort, workShort\)\)/);
  assert.match(adminHtml, /return Math\.min\(requiredMinutes, Math\.max\(lateShort, earlyOut, workShort\)\)/);
  assert.match(adminHtml, /function reportHours\(minutes, showZero = false\)/);
  assert.match(adminHtml, /const showZeroWork = outMs === inMs/);
  assert.match(adminHtml, /work: reportHours\(workMinutes, showZeroWork\)/);
  assert.match(adminHtml, /function isHalfLeaveText/);
  assert.match(adminHtml, /function reportWorkingWindowMinutes/);
  assert.match(adminHtml, /if \(inMinutes <= start \+ 10\) lateShort = 0/);
  assert.match(adminHtml, /if \(isHalfLeaveText\(leaveTaken\)\)/);
  assert.match(adminHtml, /Math\.max\(0, 240 - reportWorkingWindowMinutes\(attendanceRow, day\)\)/);
  assert.match(adminHtml, /const workShort = Math\.max\(0, requiredMinutes - Number\(attendanceRow\.actualMinutes \|\| 0\)\)/);
  assert.match(adminHtml, /return Math\.min\(requiredMinutes, Math\.max\(lateShort, earlyOut, workShort\)\)/);
  assert.doesNotMatch(adminHtml, /inMs >= endMs\) return 0/);
  assert.match(adminHtml, /REPORT_CALC_VERSION = "20260806-report-in-out-only"/);
  assert.match(adminHtml, /main \{\s+width: calc\(100% - 24px\)/);
  assert.match(adminHtml, /\.reportTable \{\s+width: 100%;\s+min-width: 0;\s+table-layout: fixed;/);
  assert.match(adminHtml, /\.employeeReport \.tableWrap \{\s+overflow-x: hidden;/);
  assert.match(adminHtml, /#monthlyReportPanel\.monthlyReportFullscreen \{[\s\S]*position: fixed;[\s\S]*inset: 0;/);
  assert.match(adminHtml, /\.monthlyReportFullscreen \.reportTable \{\s+height: 100%;\s+font-size: 12px;/);
  assert.match(adminHtml, /<select id="reportEmployeeSelect"><\/select>/);
  assert.match(adminHtml, /function setupReportEmployeeOptions/);
  assert.match(adminHtml, /const employeeRows = selectedIndex >= 0 \? \[activeEmployees\[selectedIndex\]\] : \[\]/);
  assert.match(adminHtml, /reportEmployeeSelect\.addEventListener\("change"/);
  assert.match(adminHtml, /monthlyReportArea\.classList\.toggle\("singleEmployeeReport", employeeRows\.length === 1\)/);
  assert.match(adminHtml, /document\.body\.classList\.add\("monthlyReportOpen"\)/);
  assert.match(adminHtml, /<colgroup>[\s\S]*<col style="width:13%">[\s\S]*<col style="width:22%">[\s\S]*<\/colgroup>/);
  assert.doesNotMatch(adminHtml, /return Math\.max\(lateShort, earlyOut\)/);
  assert.match(adminHtml, /function isEditableReportField/);
  assert.match(adminHtml, /function reportFieldWasEdited/);
  assert.match(adminHtml, /sameReportInstant\(approvedTimes\.clockIn, rowFirstIn\)/);
  assert.match(adminHtml, /reportEditedClockIn: Boolean\(inMarker \|\| reportSegmentRows\.some\(row => row\.clock_in_at\)\) && !correctionInWins/);
  assert.match(adminHtml, /reportEditedBreak: Boolean\(breakTime\)/);
  assert.match(adminHtml, /if \(!isEditableReportField\(field\)\) return fallback/);
  assert.match(adminHtml, /if \(reportCorrectionWins\(employeeId, dateKey, field\)\) return fallback/);
  assert.match(adminHtml, /const manualEdit = editableField && !correctionWins && \(Object\.prototype\.hasOwnProperty\.call\(monthlyReportEdits, key\) \|\| reportFieldWasEdited\(employeeId, dateKey, field\)\)/);
  assert.match(adminHtml, /if \(!isEditableReportField\(field\)\)/);
  assert.doesNotMatch(adminHtml, /editableReportCell\(employee\.id, dateKey, "break"/);
  assert.doesNotMatch(adminHtml, /editableReportCell\(employee\.id, dateKey, "resume"/);
  assert.doesNotMatch(adminHtml, /<th>Break<\/th>|<th>Resume<\/th>/);
  assert.match(adminHtml, /const liveRows = timeRows/);
  assert.match(adminHtml, /liveRows\.forEach\(row =>/);
  assert.match(adminHtml, /delete nextEdits\[reportEditKey\(employeeId, row\.dateKey, field\)\]/);
  assert.doesNotMatch(adminHtml, /const restoreRows = \[\.\.\.reportRows\.keys\(\)\]/);
  assert.match(adminHtml, /action: "save_report_attendance_times"/);
  assert.match(adminHtml, /let reportRemarks = \[\]/);
  assert.match(adminHtml, /function reportRemark/);
  assert.match(adminHtml, /data\.reportRemarks \|\| \[\]/);
  assert.match(adminHtml, /action: "save_report_remarks"/);
  assert.match(adminHtml, /remarkRows\.forEach\(row =>/);
  assert.doesNotMatch(adminHtml, /restore_report_attendance_times|restoreEmployeeMonthlyReport|data-restore-report/);
  assert.match(adminHtml, /data-cancel-report/);
  assert.match(adminHtml, /Cancelled edit \|/);
  assert.match(adminHtml, /row\.source === "admin_report_edit" \|\| row\.source === "admin_report_edit_resume"/);
  assert.match(adminHtml, /function compareReportSegments/);
  assert.match(adminHtml, /editedFields: \["in", "out"\]\.filter/);
  assert.match(adminHtml, /REPORT_TIME_FIELDS = new Set\(\["in", "out"\]\)/);
  assert.match(adminHtml, /REPORT_LEAVE_VALUES = new Set\(\["", "ANNUAL LEAVE", "HALF ANNUAL LEAVE", "MC"\]\)/);
  assert.match(adminHtml, /class="reportLeavePicker" data-report-leave-picker/);
  assert.match(adminHtml, /\["ANNUAL LEAVE", "Annual Leave"\]/);
  assert.match(adminHtml, /\["HALF ANNUAL LEAVE", "Half Annual Leave"\]/);
  assert.match(adminHtml, /\["MC", "MC"\]/);
  assert.match(adminHtml, /field === "leaveTaken"/);
  assert.match(adminHtml, /picker \? picker\.value : timeInput \? timeInput\.value\.trim\(\) : cell\.textContent\.trim\(\) \|\| ""/);
  assert.match(adminHtml, /action: "save_report_leave_taken"/);
  assert.match(adminHtml, /leaveTaken: reportRowText\(row, "leaveTaken"\)/);
  assert.match(adminHtml, /data-report-leave-picker/);
  assert.match(adminRoute, /action: "save_report_leave_taken"/);
  assert.match(adminRoute, /action: "save_report_remarks"/);
  assert.match(adminRoute, /FROM monthly_report_remarks r/);
  assert.match(adminRoute, /function saveReportRemarks/);
  assert.match(adminRoute, /ON CONFLICT\(employee_id, work_date\) DO UPDATE SET/);
  assert.match(adminRoute, /monthly_report_remark_edit/);
  assert.match(adminRoute, /INSERT INTO employees \(id, employee_code, full_name, department_id, position, phone, email, leave_entitlement_days, status\) VALUES \(\?, \?, \?, \?, \?, \?, \?, \?, 'active'\)/);
  assert.doesNotMatch(adminRoute, /leave_entitlement_days, status\) VALUES \(\?, \?, \?, \?, \?, \?, \?, 0, 'active'\)/);
  assert.match(adminRoute, /function reportLeaveSelection/);
  assert.match(adminRoute, /Leave Taken must be blank, Annual Leave, Half Annual Leave, or MC/);
  assert.match(adminRoute, /status = 'cancelled'/);
  assert.match(adminRoute, /admin_note = 'Cancelled by admin from monthly report'/);
  assert.match(adminRoute, /monthly_report_leave_edit/);
  assert.match(adminRoute, /leaveType: "leave", duration: "full_day", label: "ANNUAL LEAVE"/);
  assert.match(adminRoute, /leaveType: "leave", duration: "half_day", label: "HALF ANNUAL LEAVE"/);
  assert.match(adminRoute, /leaveType: "mc", duration: "full_day", label: "MC"/);
  assert.match(adminHtml, /contenteditable="\$\{editable \? "true" : "false"\}"/);
  assert.match(adminHtml, /maximum-scale=1\.0, user-scalable=no/);
  assert.match(adminHtml, /class="reportTimeEditor" data-report-time-input/);
  assert.doesNotMatch(adminHtml, /clearReportTime|data-clear-report-time/);
  assert.match(adminHtml, /timeInput \? timeInput\.value\.trim\(\) : cell\.textContent\.trim\(\)/);
  assert.match(adminHtml, /\.monthlyReportFullscreen \.reportLeavePicker \{\s+min-height: 0;\s+height: 16px;/);
  assert.doesNotMatch(adminHtml, /\.monthlyReportFullscreen \.reportLeavePicker:disabled/);
  assert.match(adminHtml, /refreshReportRow\(cell\.closest\("tr"\), false\)/);
  assert.match(adminHtml, /refreshReportRow\(cell\.closest\("tr"\), true\)/);
  assert.match(adminHtml, /function originalReportValue/);
  assert.match(adminHtml, /function reportFieldShouldSave/);
  assert.match(adminHtml, /return reportEditDraftKeys\.has\(reportEditKey\(employeeId, dateKey, field\)\)/);
  assert.doesNotMatch(adminHtml, /function reportFieldShouldSave[\s\S]{0,200}reportFieldWasEdited/);
  assert.match(adminHtml, /return reportFieldShouldSave\(employeeId, dateKey, field\)/);
  assert.match(adminHtml, /editedFields: \["in", "out"\]\.filter\(field => reportFieldShouldSave\(employeeId, dateKey, field\)\)/);
  assert.match(adminHtml, /if \(!cell \|\| !isEditableReportField\(cell\.dataset\.reportField\)\) return/);
  assert.match(adminHtml, /reportEditDraftKeys\.add\(reportEditKey\(cell\.dataset\.reportEmployee, cell\.dataset\.reportDate, cell\.dataset\.reportField\)\)/);
  assert.match(adminHtml, /if \(REPORT_TIME_FIELDS\.has\(cell\.dataset\.reportField\)\) refreshReportRow\(cell\.closest\("tr"\), false\)/);
  assert.match(adminHtml, /const regularSpan = Math\.max\(0, Math\.round/);
  assert.match(adminHtml, /function regularWindowStartMs/);
  assert.match(adminHtml, /clockInMs >= earlyStartMs && clockInMs <= graceEndMs \? startMs : Math\.max\(clockInMs, earlyStartMs\)/);
  assert.match(adminHtml, /const breakDeduction = day >= 1 && day <= 5 && regularSpan >= 300 \? 60 : 0/);
  assert.match(adminHtml, /scheduledDateTimeMs\(dateKey, end \+ 15\)/);
  assert.match(adminHtml, /scheduledDateTimeMs\(attendanceRow\.dateKey, end \+ 15\)/);
  assert.doesNotMatch(adminHtml, /lateShort > 60\) lateShort -= 60/);
  assert.match(adminHtml, /const regularCap = day === 6 \? 240 : 480/);
  assert.match(adminHtml, /Math\.min\(Math\.max\(0, regularSpan - breakDeduction\), regularCap\) \+ overtime/);
  assert.match(adminHtml, /const outMs = parseLiveTimestamp\(attendanceRow\.clockOut\)/);
  assert.match(adminHtml, /Math\.round\(\(endMs - outMs\) \/ 60000\)/);
  assert.doesNotMatch(adminHtml, /Math\.max\(0, end - outMinutes\)/);
  assert.match(adminHtml, /20260805-shared-attendance-day/);
  assert.doesNotMatch(adminHtml, /<th>Sche<\/th>/);
  assert.doesNotMatch(adminHtml, /<th>Diff OT<\/th>/);
  assert.doesNotMatch(adminHtml, /editableReportCell\(employee\.id, dateKey, "schedule"/);
  assert.doesNotMatch(adminHtml, /editableReportCell\(employee\.id, dateKey, "diffOt"/);
});
